// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.6.10'
    ext.kotlin_version = '1.6.0'

    repositories {
        google()
        mavenCentral()
        maven { url "https://oss.jfrog.org/libs-snapshot" }
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
        classpath 'com.android.tools.build:gradle:7.1.1'
        //noinspection GradleDynamicVersion
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:7.+"
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.18'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.38.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }

    tasks.matching {it instanceof Test}.all {
        testLogging.events = ["failed", "passed", "skipped"]
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}